theme: jekyll-theme-architect
title: Phasmophobia Tips
description: A guide to the VR horror game Phasmophobia including the items, ghosts, maps, tips, tricks and more.
google_analytics: UA-179374035-1
markdown: CommonMarkGhPages # enable collapsable panels
