theme: jekyll-theme-architect
title: Phasmophobia Tips
description: A guide to the VR horror game Phasmophobia including the items, ghosts, maps, tips, tricks and more.
markdown: CommonMarkGhPages # enable collapsable panels
